### PR TITLE
Make codelists used

### PR DESCRIPTION
**Pull request by duncandewhurst**
Addresses https://github.com/open-contracting/public-private-partnerships/issues/135

### CODE REVIEW

**Comment by jpmckinney** [comment]
@duncandewhurst Can you run apply-extensions.py to update the files that build on release-schema? Otherwise, good to merge.

**Comment by duncandewhurst** [comment]
@jpmckinney running apply-extensions.py also updated the paths to codelists in each extension readme file but I haven't committed those changes

**Comment by duncandewhurst** [comment]
OK so I ran `checkout HEAD~1` to get my local branch back to the previous commit:

> HEAD is now at 490b8cf... add milestoneCode codelist

But `push --force origin make-codelists-used` results in

> Everything up-to-date

And I still see the `update built schemas` commit on this PR

**Comment by jpmckinney** [comment]
Oh, oops, meant to be `git reset HEAD~1` then `git checkout .` and then git push… I did it now.

**Pull request merged**
