### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by jpmckinney**
Many typos in extensions weren't carried over to this repo when apply-extensions.py was run, which suggests gaps in the synchronization and maintenance of this repo.

The corrections include more serious issues like `uniqueItems` typos.

### CODE REVIEW

**Comment by jpmckinney** [comment]
See #73 and #74. We should have a process that guarantees that errors don't persist once corrected in this repo's dependencies.

**Comment by duncandewhurst** [comment]
I think this is because apply-extensions.py is running against a branch of the extension registry which is picking up the 1.1 releases of the extensions rather than the master branches which have the typo fixes.

To fix this we need to:

1. For each extension used in the PPP profile, pin the branch we want to use in the PPP extension (already done for core extensions for OCDS 1.1.1)
1. Create a branch of the extension registry for the PPP extension, referencing the branches from (1.)
1. Update [apply-extensions.py](https://github.com/open-contracting/public-private-partnerships/blob/master/schema/apply-extensions.py#L2) to reference the PPP branch of the extension registry
1. Run the build locally and commit the changes to this repo

We can then check that against this typos branch to make sure we got them all.

I'll do this once 1.1.1 is released so we can use that as the basis for the new build.

This will mean we can keep the ppp extension 'fixed' and avoid breaking translations.

I'll also document this in the standard development handbook.

**Comment by duncandewhurst** [comment]
A quick update on this (and notes for inclusion in documentation):

I have created a [ppp branch](https://github.com/open-contracting/extension_registry) of the extension registry with the entries for each extension pointing to:

* `V1.1.1` releases of core extensions
*  `ppp` releases of community extensions

I have pushed a new [update-extensions branch](https://github.com/open-contracting/public-private-partnerships/tree/update-extensions) of this repo with the following updates:

* Updated [apply-extensions.py L21](https://github.com/open-contracting/public-private-partnerships/blob/update-extensions/schema/apply-extensions.py#L21) to point to the ppp branch of the extensions registry
* Updated [apply-extensions.py L157-160](https://github.com/open-contracting/public-private-partnerships/blob/update-extensions/schema/apply-extensions.py#L157-L160) to pick up codelists from the releases referenced in the extensions registry (previously this was hard coded to pick up a master release if one existed so it was missing codelists for some extensions, e.g. bidStatus.csv) @kindly @edugomez please could you check I got this right?
* Results of running apply-extensions.py to update schema, codelists and extension docs pages

*Note:* apply-extensions.py will only work with extensions hosted under the open-contracting github organization.

Based on a spot check of the diff between the `typos` branch and `update-extensions` branch I think this has resolved the issue that this PR was trying to address.

To do:

* Add error messaging and inline documentation to apply-extensions.py
* Merge `update-extensions` into `master`
* Double check diff on this PR and then delete it
* Update Readme-Docs.md and the standard development handbook based on the notes in this thread

**Comment by jpmckinney** [comment]
I'll just re-perform the spellchecks.

**Pull request closed without merging**
