### PR TITLE
Add travis deploy

### PR DESCRIPTION
**Pull request by Bjwebb**
This deploys to `http://standard.open-contracting.org/profiles/ppp/{branch name}/en/`

e.g., for this `deploy` branch: http://standard.open-contracting.org/profiles/ppp/deploy/en/

### CODE REVIEW

**Comment by timgdavies** [comment]
Minor change, but can we make that ppp rather than ppps?

**Comment by Bjwebb** [comment]
Done

**Comment by Bjwebb** [comment]
Now that this is merged, master now gets built at http://standard.open-contracting.org/profiles/ppp/master/en/

**Comment by duncandewhurst** [comment]
@Bjwebb - the new deploy seems to be missing the version/language switcher (although the Spanish translation is built at http://standard.open-contracting.org/profiles/ppp/master/es)

**Pull request merged**
